version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - pytest -s -v -m "sanity and regression" --html=./reports/report1.html testCases/ --browser chrome
      - aws s3 cp ./reports/report1.html s3://sarthak-bucket-for-artifact-storage/report1.html

artifacts:
 type: zip
   paths:
     - '*'
  
